[package]
name = "yt"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11"
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
chrono = "*"